//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuitionManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Student = new HashSet<Student>();
        }
    
        public int ClassId { get; set; }
        public string ClassName { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public int ClassTypeId { get; set; }
        public string Shift { get; set; }
        public Nullable<bool> IsEnded { get; set; }
    
        public virtual Object Object { get; set; }
        public virtual ICollection<Student> Student { get; set; }
    }
}
