//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuitionManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.SubInvoice = new HashSet<SubInvoice>();
            this.Receipt = new HashSet<Receipt>();
        }
    
        public int InvoiceId { get; set; }
        public int StudentId { get; set; }
        public int ClassID { get; set; }
        public int ClassTypeID { get; set; }
        public int FeeLevelId { get; set; }
        public int RegisterInGroup { get; set; }
        public System.DateTime ActivatedDate { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsActivated { get; set; }
    
        public virtual FeeLevel FeeLevel { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<SubInvoice> SubInvoice { get; set; }
        public virtual ICollection<Receipt> Receipt { get; set; }
    }
}
