//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuitionManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        public Object()
        {
            this.Class1 = new HashSet<Class>();
            this.FeeLevel = new HashSet<FeeLevel>();
        }
    
        public int ObjectId { get; set; }
        public string ObjectName { get; set; }
        public string Class { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<Class> Class1 { get; set; }
        public virtual ICollection<FeeLevel> FeeLevel { get; set; }
    }
}
