//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuitionManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public Rate()
        {
            this.Receipt = new HashSet<Receipt>();
        }
    
        public int RateId { get; set; }
        public double USDRate { get; set; }
        public double VNDRate { get; set; }
        public System.DateTime RateDate { get; set; }
    
        public virtual ICollection<Receipt> Receipt { get; set; }
    }
}
