//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuitionManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.FeeAccount = new HashSet<FeeAccount>();
            this.RoleFunction = new HashSet<RoleFunction>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual ICollection<FeeAccount> FeeAccount { get; set; }
        public virtual ICollection<RoleFunction> RoleFunction { get; set; }
    }
}
