//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuitionManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubInvoice
    {
        public int SubInvoiceId { get; set; }
        public int InvoiceId { get; set; }
        public double Money { get; set; }
        public System.DateTime FeeDate { get; set; }
        public bool IsPaid { get; set; }
        public string Notes { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
