//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuitionManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwActivation
    {
        public int InvoiceId { get; set; }
        public System.DateTime ActivatedDate { get; set; }
        public Nullable<bool> IsActivated { get; set; }
        public int RegisterInGroup { get; set; }
        public string Notes { get; set; }
        public int StudentId { get; set; }
        public string StudentCode { get; set; }
        public string StudentName { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public bool Gender { get; set; }
        public int ClassID { get; set; }
        public int ObjectId { get; set; }
        public string ObjectName { get; set; }
        public int FeeLevelId { get; set; }
        public int PaidTime { get; set; }
    }
}
