//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuitionManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwInvoice
    {
        public int InvoiceId { get; set; }
        public System.DateTime ActivatedDate { get; set; }
        public int StudentId { get; set; }
        public string StudentCode { get; set; }
        public string StudentName { get; set; }
        public bool Gender { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int ClassId { get; set; }
        public string ClassName { get; set; }
        public System.DateTime DateStart { get; set; }
        public string Shift { get; set; }
        public int FeeLevelId { get; set; }
        public double TotalMoney { get; set; }
        public int PaidTime { get; set; }
        public Nullable<int> TimeOfPayment { get; set; }
        public double Money { get; set; }
        public bool IsPaid { get; set; }
        public System.DateTime FeeDate { get; set; }
        public Nullable<int> OverDay { get; set; }
        public string Notes { get; set; }
    }
}
