//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuitionManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReceipt
    {
        public int InvoiceId { get; set; }
        public int StudentId { get; set; }
        public string StudentCode { get; set; }
        public string StudentName { get; set; }
        public double PaidAmount { get; set; }
        public double TotalMoney { get; set; }
        public System.DateTime FeeDate { get; set; }
        public int ObjectId { get; set; }
        public string ObjectName { get; set; }
        public string Class { get; set; }
        public int PaidTime { get; set; }
        public string Notes { get; set; }
    }
}
